import type { NextPage } from "next";
import Head from "next/head";
import { Button } from "primereact/button";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-xl text-center text-blue-700">Hello World!</h1>
        <Button label="Click" icon="pi pi-check" />
        <Button
          label="Click"
          icon="pi pi-check"
          iconPos="right"
          className="mx-4"
        />
        <Button icon="pi pi-check" iconPos="right" />
      </main>
    </div>
  );
};

export default Home;
